apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mydb
  serviceName: "dbservice"
  template:
    metadata:
      labels:
        app: mydb
    spec:
      containers:
        - name: mydbcontainer
          image: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "Pass@123" # Replace with a secure password
          ports:
            - containerPort: 3306
  volumeClaimTemplates:
    - metadata:
        name: dbb
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
