apiVersion: v1
kind: Pod
metadata:
    name: nginxwala
spec:
    containers:
          - name: nginxwalacontainer
            image: nginx
            volumeMounts:
                - name: nginxconfigvolume
                  mountPath: /etc/nginx/conf.d/default.conf
                  subPath: default.conf

    volumes:
       - name: nginxconfigvolume
         configMap:
               name: nginx-conf
