apiVersion: v1
kind: Pod
metadata:
    name: secretesqlwala
spec:
    containers:
          - name: secretesqlwalacontainer
            image: mysql:8.0
            env: 
               - name: MYSQL_ROOT_PASSWORD
                 valueFrom: 
                      secretKeyRef:
                          name: mysecret
                          key: mysql-password
