apiVersion: apps/v1
kind: Deployment
metadata:
     name: myfirstdeployment
spec:
   replicas: 3
   selector:
      matchLabels:
          env: dev
   template:
        metadata:
             labels:
                env: dev
        spec:
           containers:
                   - name: mazanginxcont
                     image: nginx
                     ports:
                       - containerPort: 80
