apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: mazirc
spec:
   replicas: 3
   selector:
       matchLabels:
           app: myapp
   template:
       metadata:
          labels:
             app: myapp
       spec:
         containers:
               - name: mazanginxcontainer
                 image: nginx
                 ports:
                   - containerPort: 80
