apiVersion: apps/v1
kind: ReplicaSet
metadata:
    name: merirc
spec:
   replicas: 3
   selector:
       matchLabels:
           env: dev
   template:
       metadata:
          labels:
             env: dev
       spec:
         containers:
               - name: mynginxcontainer
                 image: nginx
                 ports:
                   - containerPort: 80
