apiVersion: apps/v1
kind: ReplicaSet
metadata:
     name: myrs1
spec:
   replicas: 3
   selector:
      matchLabels:
           env: testing
   template:
       metadata:
          labels:
             env: testing
       spec:
         containers:
                - name: mynginxcontain
                  image: nginx
                  ports:
                     - containerPort: 80
