apiVersion: v1
kind: Pod
metadata:
    name: nginxwala
    labels:
        app: myapp
spec:
   containers:
          - name: nginxcontainer
            image: nginx
            ports:
               - containerPort: 80
